package org.jb.y272.team0.entity;


/**
 * SysUser generated by MyEclipse - Hibernate Tools
 */

public class SysUser  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -6261343754663212034L;
	private Long usrId;
     private String usrName;
     private String usrPassword;
     private Integer usrFlag;
     private SysRole usrRole = new SysRole();


    // Constructors

    /** default constructor */
    public SysUser() {
    }

	/** minimal constructor */
    public SysUser(String usrName, String usrPassword, Integer usrFlag) {
        this.usrName = usrName;
        this.usrPassword = usrPassword;
        this.usrFlag = usrFlag;
    }
    
    /** full constructor */
    public SysUser(String usrName, String usrPassword, Integer usrFlag, SysRole sysRole) {
        this.usrName = usrName;
        this.usrPassword = usrPassword;
        this.usrFlag = usrFlag;
        this.usrRole = sysRole;
    }

   
    // Property accessors

    public Long getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }

    public String getUsrPassword() {
        return this.usrPassword;
    }
    
    public void setUsrPassword(String usrPassword) {
        this.usrPassword = usrPassword;
    }

    public Integer getUsrFlag() {
        return this.usrFlag;
    }
    
    public String getUsrFlagString(){
    	String ret = "";
    	switch(this.usrFlag){
    	case 0: ret = "已删除";break;
    	case 1: ret = "正常";break;
    	}
    	return ret;
    }
    
    public void setUsrFlag(Integer usrFlag) {
        this.usrFlag = usrFlag;
    }

    public SysRole getUsrRole() {
        return this.usrRole;
    }
    
    public void setUsrRole(SysRole role) {
        this.usrRole = role;
    }

}